### ISSUE TITLE
MozActivity 

### ISSUE THREAD

**Issue by strukturart** [arma7x/telekram#1]
if you open the app with MozActivity action, the focus () does not work in the chat list.

**Comment by arma7x** [comment]
Can explain in more detail on how reproduce this bug ?

**Comment by strukturart** [comment]
for example, if i want to share my position from my omap app, an openstreetmap link is sent to telekram.
telekram opens but you cannot see where you are in the chat list because the element does not change color although it is focused.

**Comment by arma7x** [comment]
I can't reproduce the bug of MozActivity

1) Open Gallery & SELECT any photo
2) Click Options & pick Share
3)  Then choose Telekram
4) Telekram opened via MozActivity & showing my recent chat list + INPUT BOX of search contact
5) I can navigate up/down between my recent chat list & press LeftSoftKey to focus INPUT BOX and searching my contacts

** sometimes you neeed to toggle ArrowUp/ArrowDown after searching the contact because i did't reset tabIndex to 0 after searching
